USE crm;

ALTER TABLE campaign_runs
  ADD COLUMN step_id VARCHAR(16) NULL AFTER status;

ALTER TABLE campaign_runs
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
